"""Shared domain types, errors, and utilities."""

from __future__ import annotations

from app.domain.shared.errors import (
    ActiveCaseConflictError,
    BusinessRuleViolationError,
    DomainError,
    EntityNotFoundError,
    InvalidCatalogError,
    InvalidTransitionError,
)
from app.domain.shared.ids import (
    ActividadId,
    CasoId,
    CitaId,
    CuidadorId,
    EventoId,
    NotaClinicaId,
    PacienteId,
    PlanTerapeuticoId,
    TamizajeId,
    TransicionId,
    UsuarioId,
    new_actividad_id,
    new_caso_id,
    new_cita_id,
    new_cuidador_id,
    new_evento_id,
    new_nota_clinica_id,
    new_paciente_id,
    new_plan_terapeutico_id,
    new_tamizaje_id,
    new_transicion_id,
    new_usuario_id,
)
from app.domain.shared.result import Err, Ok, Result

__all__ = [
    "ActiveCaseConflictError",
    "ActividadId",
    "BusinessRuleViolationError",
    "CasoId",
    "CitaId",
    "CuidadorId",
    "DomainError",
    "EntityNotFoundError",
    "Err",
    "EventoId",
    "InvalidCatalogError",
    "InvalidTransitionError",
    "NotaClinicaId",
    "Ok",
    "PacienteId",
    "PlanTerapeuticoId",
    "Result",
    "TamizajeId",
    "TransicionId",
    "UsuarioId",
    "new_actividad_id",
    "new_caso_id",
    "new_cita_id",
    "new_cuidador_id",
    "new_evento_id",
    "new_nota_clinica_id",
    "new_paciente_id",
    "new_plan_terapeutico_id",
    "new_tamizaje_id",
    "new_transicion_id",
    "new_usuario_id",
]
